spring.application.name=backend

spring.datasource.url=jdbc:mysql://localhost:3306/coffee_shop
spring.datasource.username=root
spring.datasource.password=ilovejesse
spring.jpa.hibernate.ddl-auto=update


